plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
theme: jekyll-theme-cayman
title: Intermediate Express Middle Session
baseurl: "education-intermediate-express-middle-session"
url: ""
